### ISSUE TITLE
Event name should be overridable.

### ISSUE THREAD

**Issue by twitchax** [tokio-rs/tracing#2696] opened 2023-08-27 08:18 UTC
### Crates

`tracing`

### Motivation

Compatibility with various otel-ish endpoints.

### Proposal

It  would be nice if the user could specify the event name in `tracing::event!`, `tracing::error!`, etc.  Right now, it appears to be set to some default, and many otel endpoints use `exception`.  Allowing the user to override this value would allow them to flag exceptional events in the otel service.

I could possibly implement this.

**Comment by davidbarsky** [comment] 2023-08-28 16:51
We're not opposed to this change, but I'm going to close this as a duplicate of https://github.com/tokio-rs/tracing/issues/1426. Feel free to take a look at the discussion there for guidance on implementing this.

**Closed by davidbarsky** 2023-08-28 16:51 UTC

**Comment by hawkw** [comment] 2023-08-28 18:16
As I mentioned in https://github.com/tokio-rs/tracing/issues/1426#issuecomment-1594664465, I'm happy to merge a PR that adds custom event names, if you're interested in submitting one!
