### ISSUE TITLE
tracing_attributes: Add an option to explicitly set parent span in #[instrument]

### ISSUE THREAD

**Issue by jaskij** [tokio-rs/tracing#2021] opened 2022-03-24 21:02 UTC
### Crates

`tracing_attributes`

### Motivation

Sometimes it's useful to be able to set the parent span when using this macro. One use case would be for structs which have their own span and want to instrument their methods.

### Proposal

Add a new argument to `tracing_attributes::instrument` to allow explicitly setting the parent span, instead of inheriting from context.

### Alternatives

Emulating the behavior of `#[instrument]` manually, which is both a lot of code and very error prone.

**Comment by hawkw** [comment] 2022-04-22 17:06
Just realized that this is also a duplicate of #879, so when we close this, we should make sure to close that issue as well.

**Closed** 2022-04-25 21:54 UTC
Labels: kind/feature, good first issue, crate/attributes
