### ISSUE TITLE
Instrument attribute with async-trait breaks include_str

### ISSUE THREAD

**Issue by Txuritan** [tokio-rs/tracing#755] opened 2020-06-18 07:48 UTC
### Version

tracing v0.1.15
tracing-futures v0.2.4

### Platform

Windows (64-bit)

### Crates

async-trait v0.1.35

### Description

When adding `#[tracing::instrument]` to a function in a `#[async_trait::async_trait]` trait implementation, `include_str` will think its in the root of the src folder when its not.

File tree:
```
src/
+-- lib.rs
+-- example/
    +-- mod.rs
    +-- text.txt
```

`lib.rs`:
```rust
mod example;

#[async_trait::async_trait]
pub trait Test {
    async fn example(&self);
}
```

`mod.rs`:
```rust
use crate::Test;

#[derive(Debug)]
pub struct Example {}


#[async_trait::async_trait]
impl Test for Example {
    #[tracing::instrument]
    async fn example(&self) {
        let _text = include_str!("text.txt");
    }
}
```

**Comment by hawkw** [comment] 2020-06-19 19:51
Hmm, that seems very weird. I'm guessing you've already tested that this cannot be reproduced with _just_ `instrument` or `async-trait`?

**Comment by Txuritan** [comment] 2020-06-19 20:20
I have, `async-trait` alone works fine (what I'm currently doing), `instrument` also works without a problem (not async though), it only happens when I add `instrument`.

**Comment by hawkw** [comment] 2020-06-19 20:40
Interesting, thanks!

@nightmared since you actually wrote the `async-trait` integration for `instrument`, perhaps you'd have more insight into this than I do?

**Comment by nightmared** [comment] 2020-06-19 21:00
Hum, that's weird, I tried it and I couldn't reproduce ?
```
src/
src/ex
src/ex/mod.rs
src/ex/text.txt
src/lib.rs
```

And it compiles just fine (this is exactly your example above, with `example` renamed as `ex` because I was lazy when creating the folder :-D).
Without the file I get this error, that shows it fetches the file in the right folder:
```
error: couldn't read src/ex/text.txt: No such file or directory (os error 2)
  --> src/ex/mod.rs:11:21
   |
11 |         let _text = include_str!("text.txt");
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Maybe I'm missing something ?

**Comment by Txuritan** [comment] 2020-06-19 21:11
Here's a [repo](https://github.com/Txuritan/tie) of the project that I used to find the cause.

I'm using the latest stable:
```
E:\git\rust\tie>rustc -V
rustc 1.44.0 (49cae5576 2020-06-01)
```

If I'm meant to be using nightly then I didn't see it anywhere.

**Comment by nightmared** [comment] 2020-06-19 21:14
It does build with nightly on my computer (and no you're not supposed to have to use nightly AFAIK). But you're right, it fails with stable !?

**Comment by nightmared** [comment] 2020-06-19 21:18
That's worrying, i will install cargo-expand (`-Zunstable-options --pretty=expanded` isn't available on stable) and see if I can undertand what's going on, but I don't guarantee much, this is fairly cryptic :)

**Comment by Txuritan** [comment] 2020-06-19 21:23
Funnily enough I tried that as well, and as it couldn't find the file it just replaced it with `()`.

**Comment by Txuritan** [comment] 2020-06-19 21:26
Considering that nightly now works and didn't before, maybe something changed in the handling of proc-macros from 1.44 to 1.46.

**Comment by nightmared** [comment] 2020-06-19 22:20
It was fixed somewhere between nightly-2020-05-15 and nightly-2020-05-30 (Understanding noghting in rustc, I falled back to doing some terrible manual bisecting to narrow the "fix time region" :-p).

**Comment by nightmared** [comment] 2020-06-19 22:43
I will try to bisect it further, if I have the time (and courage). Had I to do a completely uneducated guess, I would have said this may be related to https://github.com/rust-lang/rust/commit/d277904582d530feb4701dc76508fdf473cce8f4#diff-0e785ff001c38d0918429e6a9880f0cd ?

**Comment by nightmared** [comment] 2020-06-20 09:00
It does build with the commit I linked previously, so it was fixed before d277904.

**Comment by nightmared** [comment] 2020-06-20 12:43
I'm still in the process of narrowing it down, but with `git-bisect run` now (it's better at running scripts than I am :p).
I still have to bisect around 30 commits (so <5 steps), but it takes its time on my laptop. Anyway, we will get to the bottom of this !

**Comment by nightmared** [comment] 2020-06-20 14:52
Great ! Apparently it's https://github.com/rust-lang/rust/commit/9b2b8a5afa833795b66267684615497c9547878d, which is weird, but who am I to understand rustc anyway ? :-p

**Comment by nightmared** [comment] 2020-06-20 14:52
Do I have to open an issue on rust ?

**Comment by hawkw** [comment] 2020-06-25 20:31
Closing this as `wontfix`, since it's an upstream compiler bug and there's nothing we can really do about it (see also https://github.com/tokio-rs/tracing/issues/768#issuecomment-649793488).

**Comment by hawkw** [comment] 2020-06-25 20:31
Thanks @nightmared for all your hard work trying to figure this one out!

**Closed by hawkw** 2020-06-25 20:31 UTC

**Comment by nightmared** [comment] 2020-06-25 20:33
Well, at least it confirms that this is fixed by the same commits @taiki-e talked about in #768, so it's not time completely wasted ^^
