### ISSUE TITLE
tracing-subscriber: with_ansi(false) does not stop italics from being emitted

### ISSUE THREAD

**Issue by Noah-Kennedy** [tokio-rs/tracing#2092] opened 2022-04-25 19:09 UTC
As discussed on the discord, setting `with_ansi(false)` does not disable ansi italics, only ansi colors.

**Comment by hawkw** [comment] 2022-04-25 20:05
just putting this here so it's written down for later: on Discord, @Noah-Kennedy said that this appears to have regressed in `tracing-subscriber` v0.3.2 — probably in https://github.com/tokio-rs/tracing/pull/1702.

**Comment by hawkw** [comment] 2022-04-25 20:08
looking at the code, this certainly _looks_ like it should do the right thing, if the writer's `with_ansi` flag is set correctly: https://github.com/tokio-rs/tracing/blob/eff932d4b4f9a7a20b3eb0f7b8b201d59d9fb6c1/tracing-subscriber/src/fmt/format/mod.rs#L406-L415

so, @Noah-Kennedy, i'd be curious to see how you're configuring the subscriber, and if there's a specific way of configuring it that has this issue, or if it always occurs. i'm wondering if there's an issue where the ANSI flag is not propagated correctly in some specific configuration of settings. a MCRE would be very helpful!

**Comment by Noah-Kennedy** [comment] 2022-04-25 20:42
@hawkw here:
```rust
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;

#[tracing::instrument]
fn say_hi(name: &str) {
    tracing::info!("Hi, {}", name);
}

fn main() {
    let l0 = tracing_subscriber::fmt::layer();

    let layer = tracing_subscriber::fmt::layer()
        .with_ansi(false);

    tracing_subscriber::registry().with(l0).with(layer).init();

    say_hi("Mr. Error")
}
```

**Comment by hawkw** [comment] 2022-04-25 20:45
Ah, based on your observation on Discord that this only occurs when there are multiple `fmt` layers, and the behavior is dependent on ordering, I believe this is a duplicate of https://github.com/tokio-rs/tracing/issues/1817.

**Comment by hawkw** [comment] 2022-04-25 20:46
I should have asked if there were multiple `fmt` layers using the same formatter...

**Comment by davidbarsky** [comment] 2022-04-25 20:59
i'll close this issue as a duplicate of #1817.

**Closed by davidbarsky** 2022-04-25 20:59 UTC
Labels: kind/bug, crate/subscriber
